name: 'Unstale Issue'

on:
  issues:
    types: [ reopened ]
  issue_comment:
    types: [ created ]

jobs:
  remove-stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: >-
      github.event.issue.state == 'open' &&
      (contains(github.event.issue.labels.*.name, 'lifecycle/stale') || 
       contains(github.event.issue.labels.*.name, 'lifecycle/rotten'))
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5

      - name: 'Remove stale labels'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Removing 'stale' label from issue #${{ github.event.issue.number }}"
          gh issue edit ${{ github.event.issue.number }} --remove-label "lifecycle/stale,lifecycle/rotten"
